# Generated by Django 3.2.20 on 2023-09-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_conversation_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='receiver',
            new_name='title',
        ),
    ]
