# Generated by Django 3.2.20 on 2023-09-10 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_rename_receiver_conversation_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 10, 7, 13, 51, 647421, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
