# Generated by Django 3.2.20 on 2023-09-13 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_auto_20230910_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='messagestatus',
            name='user',
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
